baseURL = 'https://henglgh.github.io/articles'
languageCode = 'en-us'
timeZone = "Asia/Shanghai"
title = '阿根'

theme="articles"
copyright = "© 阿根"

# 忽略 themes 目录下的 content 目录
ignoreFiles = ["themes/.*/content/.*"]

[params]
  katex = true
  mode = "toggle"
  useCDN = false
  [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/henglgh/articles"

[outputs]
  home = ["HTML", "JSON"]

[menus]
  [[menu.main]]
    #name = "Archive"
    name = "tag"
    url = "/tags"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
  [markup.highlight]
    noClasses = false
    tabWidth = 2
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6

[pagination]
  disablePagination = true

[taxonomies]
  tag = 'tags'
